import os

S3_LOCATION = 's3.amazonaws.com'
S3_KEY = 'AKIAJ3WTOWBSWNVKNLCQ'
S3_SECRET = '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'
S3_UPLOAD_DIRECTORY = ''
S3_BUCKET = 'robojoker'

SECRET_KEY = "FLASK_SECRET_KEY"
DEBUG = True
PORT = 5000